// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

abstract open class AbstractCaverphone <: StringEncoder {
    // Fields Begin
    // Fields End

    // Methods Begin
    public init() {
        throw Exception('TODO')
    }

    public func encode(source: Any): Any {
        throw Exception('TODO')
    }

    public func isEncodeEqual(str1: String, str2: String): Bool {
        throw Exception('TODO')
    }

    // Methods End
}

