// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class DoubleMetaphone2Test {
    // Fields Begin
    static let ALTERNATE_INDEX: Int64 = throw Exception('TODO')
    static let PRIMARY_INDEX: Int64 = throw Exception('TODO')
    static let TEST_DATA: Array<Array<String>> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private func checkDoubleMetaphone(typeIndex: Int64, alternate: Bool): Unit {
        throw Exception('TODO')
    }

    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    public func testDoubleMetaphoneAlternate(): Unit {
        throw Exception('TODO')
    }

    public func testDoubleMetaphonePrimary(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

