// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class MetaphoneTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func assertIsMetaphoneEqual(source: String, matches: Array<String>): Unit {
        throw Exception('TODO')
    }

    public func assertMetaphoneEqual(pairs: Array<Array<String>>): Unit {
        throw Exception('TODO')
    }

    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqual1(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqual2(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualAero(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualWhite(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualAlbert(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualGary(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualJohn(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualKnight(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualMary(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualParis(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualPeter(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualRay(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualSusan(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualWright(): Unit {
        throw Exception('TODO')
    }

    public func testIsMetaphoneEqualXalan(): Unit {
        throw Exception('TODO')
    }

    public func testMetaphone(): Unit {
        throw Exception('TODO')
    }

    public func testWordEndingInMB(): Unit {
        throw Exception('TODO')
    }

    public func testDiscardOfSCEOrSCIOrSCY(): Unit {
        throw Exception('TODO')
    }

    public func testWhy(): Unit {
        throw Exception('TODO')
    }

    public func testWordsWithCIA(): Unit {
        throw Exception('TODO')
    }

    public func testTranslateOfSCHAndCH(): Unit {
        throw Exception('TODO')
    }

    public func testTranslateToJOfDGEOrDGIOrDGY(): Unit {
        throw Exception('TODO')
    }

    public func testDiscardOfSilentHAfterG(): Unit {
        throw Exception('TODO')
    }

    public func testDiscardOfSilentGN(): Unit {
        throw Exception('TODO')
    }

    public func testPHTOF(): Unit {
        throw Exception('TODO')
    }

    public func testSHAndSIOAndSIAToX(): Unit {
        throw Exception('TODO')
    }

    public func testTIOAndTIAToX(): Unit {
        throw Exception('TODO')
    }

    public func testTCH(): Unit {
        throw Exception('TODO')
    }

    public func testExceedLength(): Unit {
        throw Exception('TODO')
    }

    public func testSetMaxLengthWithTruncation(): Unit {
        throw Exception('TODO')
    }

    public func validateFixture(pairs: Array<Array<String>>): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

