// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class NysiisTest {
    // Fields Begin
    let fullNysiis: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private func assertEncodings(): Unit {
        throw Exception('TODO')
    }

    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    private func encodeAll(strings: Array<String>, expectedEncoding: String): Unit {
        throw Exception('TODO')
    }

    public func testBran(): Unit {
        throw Exception('TODO')
    }

    public func testCap(): Unit {
        throw Exception('TODO')
    }

    public func testDad(): Unit {
        throw Exception('TODO')
    }

    public func testDan(): Unit {
        throw Exception('TODO')
    }

    public func testDropBy(): Unit {
        throw Exception('TODO')
    }

    public func testFal(): Unit {
        throw Exception('TODO')
    }

    public func testOthers(): Unit {
        throw Exception('TODO')
    }

    public func testRule1(): Unit {
        throw Exception('TODO')
    }

    public func testRule2(): Unit {
        throw Exception('TODO')
    }

    public func testRule4Dot1(): Unit {
        throw Exception('TODO')
    }

    public func testRule4Dot2(): Unit {
        throw Exception('TODO')
    }

    public func testRule5(): Unit {
        throw Exception('TODO')
    }

    public func testRule6(): Unit {
        throw Exception('TODO')
    }

    public func testRule7(): Unit {
        throw Exception('TODO')
    }

    public func testSnad(): Unit {
        throw Exception('TODO')
    }

    public func testSnat(): Unit {
        throw Exception('TODO')
    }

    public func testSpecialBranches(): Unit {
        throw Exception('TODO')
    }

    public func testTranan(): Unit {
        throw Exception('TODO')
    }

    public func testTrueVariant(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

