// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class SoundexTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    public func testB650(): Unit {
        throw Exception('TODO')
    }

    public func testBadCharacters(): Unit {
        throw Exception('TODO')
    }

    public func testDifference(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeBasic(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeBatch2(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeBatch3(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeBatch4(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeIgnoreApostrophes(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeIgnoreHyphens(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeIgnoreTrimmable(): Unit {
        throw Exception('TODO')
    }

    public func testHWRuleEx1(): Unit {
        throw Exception('TODO')
    }

    public func testHWRuleEx2(): Unit {
        throw Exception('TODO')
    }

    public func testHWRuleEx3(): Unit {
        throw Exception('TODO')
    }

    public func testMsSqlServer1(): Unit {
        throw Exception('TODO')
    }

    public func testMsSqlServer2(): Unit {
        throw Exception('TODO')
    }

    public func testMsSqlServer3(): Unit {
        throw Exception('TODO')
    }

    public func testNewInstance(): Unit {
        throw Exception('TODO')
    }

    public func testNewInstance2(): Unit {
        throw Exception('TODO')
    }

    public func testNewInstance3(): Unit {
        throw Exception('TODO')
    }

    public func testSoundexUtilsConstructable(): Unit {
        throw Exception('TODO')
    }

    public func testSoundexUtilsNullBehaviour(): Unit {
        throw Exception('TODO')
    }

    public func testUsEnglishStatic(): Unit {
        throw Exception('TODO')
    }

    public func testUsMappingEWithAcute(): Unit {
        throw Exception('TODO')
    }

    public func testUsMappingOWithDiaeresis(): Unit {
        throw Exception('TODO')
    }

    public func testWikipediaAmericanSoundex(): Unit {
        throw Exception('TODO')
    }

    public func testGenealogy(): Unit {
        throw Exception('TODO')
    }

    public func testSimplifiedSoundex(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

