// Package: jansi
package jansi

// Imports Begin
// Imports End

@Test
class AnsiTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testSetEnabled(): Unit {
        throw Exception('TODO')
    }

    public func testClone(): Unit {
        throw Exception('TODO')
    }

    public func testApply(): Unit {
        throw Exception('TODO')
    }

    public func testScrollUp(x: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testScrollDown(x: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testCursor(x: Int64, y: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testCursorToColumn(x: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testCursorUp(y: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testCursorDown(y: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testCursorRight(x: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testCursorLeft(x: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testCursorMove(x: Int64, y: Int64, expected: String): Unit {
        throw Exception('TODO')
    }

    public func testColorDisabled(): Unit {
        throw Exception('TODO')
    }

    public func testAnsiMainWithNoConsole(): Unit {
        throw Exception('TODO')
    }

    private static func assertAnsi(expected: String, actual: Any): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

