// Package: jansi
package jansi

// Imports Begin
import jansi.io.AnsiOutputStream
import jansi.io.AnsiOutputStream_IoRunnable
import jansi.io.AnsiOutputStream_WidthSupplier
// Imports End

@Test
open class AnsiOutputStreamTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public open func canHandleSgrsWithMultipleOptions(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

