// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

open class NameType {
    // Fields Begin
    var ASHKENAZI: Any = throw Exception('TODO')
    var GENERIC: Any = throw Exception('TODO')
    var SEPHARDIC: Any = throw Exception('TODO')
    let name: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    init(name: String) {
        throw Exception('TODO')
    }

    public func getName(): String {
        throw Exception('TODO')
    }

    // Methods End
}

