// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

@Test
open class PhoneticEngineTest {
    // Fields Begin
    static let TEN: Int64 = throw Exception('TODO')
    let concat: Bool = throw Exception('TODO')
    let name: String = throw Exception('TODO')
    let nameType: Any = throw Exception('TODO')
    let phoneticExpected: String = throw Exception('TODO')
    let ruleType: Any = throw Exception('TODO')
    let maxPhonemes: Int64 = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public static func data(): ArrayList<Array<Any>> {
        throw Exception('TODO')
    }

    public init(name: String, phoneticExpected: String, nameType: Any, ruleType: Any, concat: Bool, maxPhonemes: Int64) {
        throw Exception('TODO')
    }

    public func testEncode(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

