// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

open class RuleType {
    // Fields Begin
    var APPROX: Any = throw Exception('TODO')
    var EXACT: Any = throw Exception('TODO')
    var RULES: Any = throw Exception('TODO')
    let name: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    init(name: String) {
        throw Exception('TODO')
    }

    public func getName(): String {
        throw Exception('TODO')
    }

    // Methods End
}

