// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class Caverphone1Test {
    // Fields Begin
    // Fields End

    // Methods Begin
    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    public func testCaverphoneRevisitedCommonCodeAT1111(): Unit {
        throw Exception('TODO')
    }

    public func testEndMb(): Unit {
        throw Exception('TODO')
    }

    public func testIsCaverphoneEquals(): Unit {
        throw Exception('TODO')
    }

    public func testSpecificationV1Examples(): Unit {
        throw Exception('TODO')
    }

    public func testWikipediaExamples(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

