// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class ColognePhoneticTest {
    // Fields Begin
    static let TESTSET: Set<String> = throw Exception('TODO')
    static let MATCHES: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private static func hasTestCase(re: String): Bool {
        throw Exception('TODO')
    }

    public static func finishTests(): Unit {
        throw Exception('TODO')
    }

    public func checkEncoding(expected: String, source: String): Unit {
        throw Exception('TODO')
    }

    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    public func testCanFail(): Unit {
        throw Exception('TODO')
    }

    public func testAabjoe(): Unit {
        throw Exception('TODO')
    }

    public func testAaclan(): Unit {
        throw Exception('TODO')
    }

    public func testAychlmajrForCodec122(): Unit {
        throw Exception('TODO')
    }

    public func testEdgeCases(): Unit {
        throw Exception('TODO')
    }

    public func testExamples(): Unit {
        throw Exception('TODO')
    }

    public func testHyphen(): Unit {
        throw Exception('TODO')
    }

    public func testIsEncodeEquals(): Unit {
        throw Exception('TODO')
    }

    public func testVariationsMella(): Unit {
        throw Exception('TODO')
    }

    public func testVariationsMeyer(): Unit {
        throw Exception('TODO')
    }

    public func testSpecialCharsBetweenSameLetters(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

main(): Unit {
    throw Exception('TODO')
}
