// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class DaitchMokotoffSoundexTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    private func soundex(source: String): String {
        throw Exception('TODO')
    }

    private func encode(source: String): String {
        throw Exception('TODO')
    }

    public func testAccentedCharacterFolding(): Unit {
        throw Exception('TODO')
    }

    public func testAdjacentCodes(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeBasic(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeIgnoreApostrophes(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeIgnoreHyphens(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeIgnoreTrimmable(): Unit {
        throw Exception('TODO')
    }

    public func testSoundexBasic(): Unit {
        throw Exception('TODO')
    }

    public func testSoundexBasic2(): Unit {
        throw Exception('TODO')
    }

    public func testSoundexBasic3(): Unit {
        throw Exception('TODO')
    }

    public func testSpecialRomanianCharacters(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

