// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class DoubleMetaphoneTest {
    // Fields Begin
    static let FIXTURE: Array<Array<String>> = throw Exception('TODO')
    static let MATCHES: Array<Array<String>> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private func assertDoubleMetaphone(expected: String, source: String): Unit {
        throw Exception('TODO')
    }

    public func assertDoubleMetaphoneAlt(expected: String, source: String): Unit {
        throw Exception('TODO')
    }

    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    public func doubleMetaphoneEqualTest(pairs: Array<Array<String>>, useAlternate: Bool): Unit {
        throw Exception('TODO')
    }

    public func doubleMetaphoneNotEqualTest(alternate: Bool): Unit {
        throw Exception('TODO')
    }

    public func testCCedilla(): Unit {
        throw Exception('TODO')
    }

    public func testCodec184(): Unit {
        throw Exception('TODO')
    }

    public func testDoubleMetaphone(): Unit {
        throw Exception('TODO')
    }

    public func testEmpty(): Unit {
        throw Exception('TODO')
    }

    public func testIsDoubleMetaphoneEqualBasic(): Unit {
        throw Exception('TODO')
    }

    public func testIsDoubleMetaphoneEqualExtended1(): Unit {
        throw Exception('TODO')
    }

    public func testIsDoubleMetaphoneEqualExtended2(): Unit {
        throw Exception('TODO')
    }

    public func testIsDoubleMetaphoneEqualExtended3(): Unit {
        throw Exception('TODO')
    }

    public func testIsDoubleMetaphoneEqualWithMATCHES(): Unit {
        throw Exception('TODO')
    }

    public func testIsDoubleMetaphoneNotEqual(): Unit {
        throw Exception('TODO')
    }

    public func testNTilde(): Unit {
        throw Exception('TODO')
    }

    public func testSetMaxCodeLength(): Unit {
        throw Exception('TODO')
    }

    public func validateFixture(pairs: Array<Array<String>>): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

