// Package: commons_codec.language
package commons_codec.language

// Imports Begin
// Imports End

@Test
open class RefinedSoundexTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    public func testDifference(): Unit {
        throw Exception('TODO')
    }

    public func testEncode(): Unit {
        throw Exception('TODO')
    }

    public func testGetMappingCodeNonLetter(): Unit {
        throw Exception('TODO')
    }

    public func testNewInstance(): Unit {
        throw Exception('TODO')
    }

    public func testNewInstance2(): Unit {
        throw Exception('TODO')
    }

    public func testNewInstance3(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

