// Package: commons_cli.bug
package commons_cli.bug

// Imports Begin
// Imports End

@Test
open class BugCLI266Test {
    // Fields Begin
    let insertedOrder: ArrayList<String> = throw Exception('TODO')
    let sortOrder: ArrayList<String> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private func buildOptionsGroup(options: Options): Unit {
        throw Exception('TODO')
    }

    private func getOptions(): Options {
        throw Exception('TODO')
    }

    public func testOptionComparatorDefaultOrder(): Unit {
        throw Exception('TODO')
    }

    public func testOptionComparatorInsertedOrder(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

