// Package: jansi
package jansi

// Imports Begin
import std.fs.*
import std.io.*
// Imports End

public open class AnsiMain {
    // Fields Begin
    // Fields End

    // Methods Begin
    private static func getJansiVersion(): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    private static func diagnoseTty(stderr: Bool): Unit {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    private static func testAnsi(stderr: Bool): Unit {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    private static func getPomPropertiesVersion(path: String): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    private static func printJansiLogoDemo(): Unit {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    private static func writeFileContent(f: File): Unit {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    private static func closeQuietly(c: Any): Unit {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    // Methods End
}

