// Package: jansi
package jansi

// Imports Begin

// Imports End

@Test
open class AnsiRendererTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    static func setUp(): Unit {
        throw Exception('TODO')
    }

    public open func testTest(): Unit {
        throw Exception('TODO')
    }

    public open func testRender(): Unit {
        throw Exception('TODO')
    }

    public open func testRenderCodes(): Unit {
        throw Exception('TODO')
    }

    public open func testRender2(): Unit {
        throw Exception('TODO')
    }

    public open func testRender3(): Unit {
        throw Exception('TODO')
    }

    public open func testRender4(): Unit {
        throw Exception('TODO')
    }

    public open func testRender5(): Unit {
        throw Exception('TODO')
    }

    public open func testRenderNothing(): Unit {
        throw Exception('TODO')
    }

    public open func testRenderInvalidMissingEnd(): Unit {
        throw Exception('TODO')
    }

    public open func testRenderInvalidEndBeforeStart(): Unit {
        throw Exception('TODO')
    }

    public open func testRenderInvalidMissingText(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

