// Package: jansi
package jansi

// Imports Begin
import jansi.io.AnsiOutputStream
import jansi.io.AnsiOutputStream_IoRunnable
import jansi.io.AnsiOutputStream_WidthSupplier
import jansi.io.AnsiProcessor
// Imports End

@Test
public open class EncodingTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public open func testEncoding8859(): Unit {
        throw Exception('TODO')
    }

    public open func testEncodingUtf8(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

