// Package: commons_codec
package commons_codec

// Imports Begin
// Imports End

@Test
abstract open class BinaryEncoderAbstractTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    protected func makeEncoder(): Any {
        throw Exception('TODO')
    }

    public func testEncodeEmpty(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeNull(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

