// Package: commons_codec
package commons_codec

// Imports Begin
// Imports End

@Test
open class CharsetsTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testToCharset(): Unit {
        throw Exception('TODO')
    }

    public func testIso8859_1(): Unit {
        throw Exception('TODO')
    }

    public func testUsAscii(): Unit {
        throw Exception('TODO')
    }

    public func testUtf16(): Unit {
        throw Exception('TODO')
    }

    public func testUtf16Be(): Unit {
        throw Exception('TODO')
    }

    public func testUtf16Le(): Unit {
        throw Exception('TODO')
    }

    public func testUtf8(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

