// Package: commons_codec
package commons_codec

// Imports Begin
// Imports End

open class Charsets {
    // Fields Begin
    static let UTF_16: Any = throw Exception('TODO')
    static let UTF_16BE: Any = throw Exception('TODO')
    static let UTF_16LE: Any = throw Exception('TODO')
    static let UTF_8: Any = throw Exception('TODO')
    static let ISO_8859_1: Any = throw Exception('TODO')
    static let US_ASCII: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public static func toCharset(charset: Any): Any {
        throw Exception('TODO')
    }

    public static func toCharset(charset: String): Any {
        throw Exception('TODO')
    }

    // Methods End
}

