// Package: commons_codec
package commons_codec

// Imports Begin
// Imports End

@Test
open class EncoderExceptionTest {
    // Fields Begin
    static let MSG: String = throw Exception('TODO')
    static let t: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testConstructor0(): Unit {
        throw Exception('TODO')
    }

    public func testConstructorString(): Unit {
        throw Exception('TODO')
    }

    public func testConstructorStringThrowable(): Unit {
        throw Exception('TODO')
    }

    public func testConstructorThrowable(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

