// Package: commons_codec
package commons_codec

// Imports Begin
// Imports End

open class StringEncoderComparator <: Comparator {
    // Fields Begin
    let stringEncoder: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public init() {
        throw Exception('TODO')
    }

    public init(stringEncoder: Any) {
        throw Exception('TODO')
    }

    public func compare(o1: Any, o2: Any): Int64 {
        throw Exception('TODO')
    }

    // Methods End
}

