// Package: commons_codec
package commons_codec

// Imports Begin
// Imports End

@Test
open class StringEncoderComparatorTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testComparatorWithSoundex(): Unit {
        throw Exception('TODO')
    }

    public func testComparatorWithDoubleMetaphone(): Unit {
        throw Exception('TODO')
    }

    public func testComparatorWithDoubleMetaphoneAndInvalidInput(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

