// Package: minimal
package minimal

// Imports Begin
import std.collection.ArrayList
import std.collection.HashMap
import std.collection.HashSet
import std.collection.List
import std.collection.Set
// Imports End

@Test
open class AppTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    open func greetShouldReturnExpectedString(): Unit {
        throw Exception('TODO')
    }

    open func addShouldSumTwoNumbers(): Unit {
        throw Exception('TODO')
    }

    open func addWithDependencyShouldMutateInputsAndReturnTaggedResult(): Unit {
        throw Exception('TODO')
    }

    open func counterShouldMutateStaticState(): Unit {
        throw Exception('TODO')
    }

    open func appendTaggedValueShouldMutateInputList(): Unit {
        throw Exception('TODO')
    }

    open func bumpBoxShouldMutateObjectField(): Unit {
        throw Exception('TODO')
    }

    open func filterAllowedShouldReturnOnlyAllowedItems(): Unit {
        throw Exception('TODO')
    }

    open func scoreOfShouldReturnMappedValue(): Unit {
        throw Exception('TODO')
    }

    open func sumBufferShouldSumUnsignedBytes(): Unit {
        throw Exception('TODO')
    }

    open func readAllShouldReturnFullContent(): Unit {
        throw Exception('TODO')
    }

    open func appendLabelShouldMutateWriter(): Unit {
        throw Exception('TODO')
    }

    open func describeScoreShouldFormatMultiFieldObject(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

