// Package: JavaFeatureTest
package JavaFeatureTest

// Imports Begin
// Imports End

open class BaseClass {
    // Fields Begin
    var name: String = throw Exception('TODO')
    // Fields End

    // Static Initializer Begin
    static init() {
        throw Exception('TODO')
    }

    // Static Initializer End

    // Methods Begin
    public init() {
        throw Exception('TODO')
    }

    public init(name: String) {
        throw Exception('TODO')
    }

    public open func getName(): String {
        throw Exception('TODO')
    }

    public open func introduce(): String {
        throw Exception('TODO')
    }

    // Methods End
}

