// Package: JavaFeatureTest
package JavaFeatureTest

// Imports Begin
// Imports End

open class Bird <: Animal {
    // Fields Begin
    var wingSpan: Int64 = throw Exception('TODO')
    // Fields End

    // Static Initializer Begin
    static init() {
        throw Exception('TODO')
    }

    // Static Initializer End

    // Methods Begin
    public init() {
        throw Exception('TODO')
    }

    public init(name: String) {
        throw Exception('TODO')
    }

    public init(name: String, age: Int64, wingSpan: Int64) {
        throw Exception('TODO')
    }

    public open func getWingSpan(): Int64 {
        throw Exception('TODO')
    }

    public open func fly(): String {
        throw Exception('TODO')
    }

    public override func speak(): String {
        throw Exception('TODO')
    }

    // Methods End
}

