// Package: JavaFeatureTest
package JavaFeatureTest

// Imports Begin
// Imports End

@Test
open class CalculatorTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public open func testConstructorOverloadNoArgs(): Unit {
        throw Exception('TODO')
    }

    public open func testConstructorOverloadOneArg(): Unit {
        throw Exception('TODO')
    }

    public open func testConstructorOverloadTwoArgs(): Unit {
        throw Exception('TODO')
    }

    public open func testMethodOverloadInt(): Unit {
        throw Exception('TODO')
    }

    public open func testMethodOverloadDouble(): Unit {
        throw Exception('TODO')
    }

    public open func testMethodOverloadThreeArgs(): Unit {
        throw Exception('TODO')
    }

    public open func testMethodOverloadString(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

