// Package: JavaFeatureTest
package JavaFeatureTest

// Imports Begin
// Imports End

open class CastingUtils {
    // Fields Begin
    // Fields End

    // Static Initializer Begin
    static init() {
                print("Static initializer: CastingUtils loaded")
    }

    // Static Initializer End

    // Methods Begin
    public static func checkType(obj: Any): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    public static func safeCheck(obj: Any): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    public static func upcast(obj: Any): Any {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    public static func downcast(obj: Any): Any {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    // Methods End
}

