// Package: JavaFeatureTest
package JavaFeatureTest

// Imports Begin
// Imports End

open class DerivedClass <: BaseClass {
    // Fields Begin
    var value: Int64 = throw Exception('TODO')
    // Fields End

    // Static Initializer Begin
    static init() {
        throw Exception('TODO')
    }

    // Static Initializer End

    // Methods Begin
    public init() {
        throw Exception('TODO')
    }

    public init(name: String, value: Int64) {
        throw Exception('TODO')
    }

    public open func getValue(): Int64 {
        throw Exception('TODO')
    }

    public override func introduce(): String {
        throw Exception('TODO')
    }

    // Methods End
}

