// Package: JavaFeatureTest
package JavaFeatureTest

// Imports Begin
// Imports End

open class Dog <: Animal {
    // Fields Begin
    var breed: String = throw Exception('TODO')
    // Fields End

    // Static Initializer Begin
    static init() {
        throw Exception('TODO')
    }

    // Static Initializer End

    // Methods Begin
    public init() {
        throw Exception('TODO')
    }

    public init(name: String) {
        throw Exception('TODO')
    }

    public init(name: String, age: Int64) {
        throw Exception('TODO')
    }

    public init(name: String, age: Int64, breed: String) {
        throw Exception('TODO')
    }

    public open func getBreed(): String {
        throw Exception('TODO')
    }

    public override func speak(): String {
        throw Exception('TODO')
    }

    public open func fetch(): String {
        throw Exception('TODO')
    }

    // Methods End
}

