// Package: JavaFeatureTest
package JavaFeatureTest

// Imports Begin
// Imports End

open class Person {
    // Fields Begin
    var name: String = throw Exception('TODO')
    var age: Int64 = throw Exception('TODO')
    var id: String = throw Exception('TODO')
    // Fields End

    // Static Initializer Begin
    static init() {
        throw Exception('TODO')
    }

    // Static Initializer End

    // Methods Begin
    public init(name: String, age: Int64, id: String) {
        throw Exception('TODO')
    }

    public open func getName(): String {
        throw Exception('TODO')
    }

    public open func getAge(): Int64 {
        throw Exception('TODO')
    }

    public open func getId(): String {
        throw Exception('TODO')
    }

    public open func toString(): String {
        throw Exception('TODO')
    }

    public open func equals(obj: Any): Bool {
        throw Exception('TODO')
    }

    public open func hashCode(): Int64 {
        throw Exception('TODO')
    }

    // Methods End
}

