// Package: JavaFeatureTest
package JavaFeatureTest

// Imports Begin
// Imports End

open class StringUtils {
    // Fields Begin
    // Fields End

    // Static Initializer Begin
    static init() {
                print("Static initializer: StringUtils class loaded")
    }

    // Static Initializer End

    // Methods Begin
    public static func join(delimiter: String): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    public static func combine(): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    public static func sum(): Int64 {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    public static func format(prefix: String, count: Int64): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    // Methods End
}

