// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

open class Base16InputStream <: BaseNCodecInputStream {
    // Fields Begin
    // Fields End

    // Methods Begin
    public init(in: InputStream) {
        throw Exception('TODO')
    }

    public init(in: InputStream, doEncode: Bool) {
        throw Exception('TODO')
    }

    public init(in: InputStream, doEncode: Bool, lowerCase: Bool) {
        throw Exception('TODO')
    }

    public init(in: InputStream, doEncode: Bool, lowerCase: Bool, decodingPolicy: Any) {
        throw Exception('TODO')
    }

    // Methods End
}

