// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class Base64InputStreamTest {
    // Fields Begin
    static let ENCODED_B64: String = throw Exception('TODO')
    static let CRLF: Array<Int8> = throw Exception('TODO')
    static let LF: Array<Int8> = throw Exception('TODO')
    static let STRING_FIXTURE: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testCodec130(): Unit {
        throw Exception('TODO')
    }

    public func testCodec105(): Unit {
        throw Exception('TODO')
    }

    public func testCodec101(): Unit {
        throw Exception('TODO')
    }

    public func testInputStreamReader(): Unit {
        throw Exception('TODO')
    }

    public func testCodec98NPE(): Unit {
        throw Exception('TODO')
    }

    public func testAvailable(): Unit {
        throw Exception('TODO')
    }

    public func testBase64EmptyInputStreamMimeChuckSize(): Unit {
        throw Exception('TODO')
    }

    public func testBase64EmptyInputStreamPemChuckSize(): Unit {
        throw Exception('TODO')
    }

    private func testBase64EmptyInputStream(chuckSize: Int64): Unit {
        throw Exception('TODO')
    }

    public func testBase64InputStreamByChunk(): Unit {
        throw Exception('TODO')
    }

    public func testBase64InputStreamByteByByte(): Unit {
        throw Exception('TODO')
    }

    private func testByChunk(encoded: Array<Int8>, decoded: Array<Int8>, chunkSize: Int64, separator: Array<Int8>): Unit {
        throw Exception('TODO')
    }

    private func testByteByByte(encoded: Array<Int8>, decoded: Array<Int8>, chunkSize: Int64, separator: Array<Int8>): Unit {
        throw Exception('TODO')
    }

    public func testMarkSupported(): Unit {
        throw Exception('TODO')
    }

    public func testReadMultipleBufferSizes(): Unit {
        throw Exception('TODO')
    }

    public func testRead0(): Unit {
        throw Exception('TODO')
    }

    public func testReadNull(): Unit {
        throw Exception('TODO')
    }

    public func testReadOutOfBounds(): Unit {
        throw Exception('TODO')
    }

    public func testSkipBig(): Unit {
        throw Exception('TODO')
    }

    public func testSkipNone(): Unit {
        throw Exception('TODO')
    }

    public func testSkipPastEnd(): Unit {
        throw Exception('TODO')
    }

    public func testSkipToEnd(): Unit {
        throw Exception('TODO')
    }

    public func testSkipWrongArgument(): Unit {
        throw Exception('TODO')
    }

    public func testStrictDecoding(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

