// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class Base16OutputStreamTest {
    // Fields Begin
    static let STRING_FIXTURE: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testBase16EmptyOutputStream(): Unit {
        throw Exception('TODO')
    }

    public func testBase16OutputStreamByChunk(): Unit {
        throw Exception('TODO')
    }

    public func testBase16OutputStreamByteByByte(): Unit {
        throw Exception('TODO')
    }

    private open func testByChunk(encoded: Array<Int8>, decoded: Array<Int8>): Unit {
        throw Exception('TODO')
    }

    private open func testByChunk(encoded: Array<Int8>, decoded: Array<Int8>, lowerCase: Bool): Unit {
        throw Exception('TODO')
    }

    private open func testByteByByte(encoded: Array<Int8>, decoded: Array<Int8>): Unit {
        throw Exception('TODO')
    }

    private open func testByteByByte(encoded: Array<Int8>, decoded: Array<Int8>, lowerCase: Bool): Unit {
        throw Exception('TODO')
    }

    public func testWriteOutOfBounds(): Unit {
        throw Exception('TODO')
    }

    public func testWriteToNullCoverage(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

