// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class BinaryCodecTest {
    // Fields Begin
    static let CHARSET_UTF8: Any = throw Exception('TODO')
    static let BIT_0: Int64 = throw Exception('TODO')
    static let BIT_1: Int64 = throw Exception('TODO')
    static let BIT_2: Int64 = throw Exception('TODO')
    static let BIT_3: Int64 = throw Exception('TODO')
    static let BIT_4: Int64 = throw Exception('TODO')
    static let BIT_5: Int64 = throw Exception('TODO')
    static let BIT_6: Int64 = throw Exception('TODO')
    static let BIT_7: Int64 = throw Exception('TODO')
    var instance: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func tearDown(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeObjectException(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeObject(): Unit {
        throw Exception('TODO')
    }

    func assertDecodeObject(bits: Array<Int8>, encodeMe: String): Unit {
        throw Exception('TODO')
    }

    public func testDecodeByteArray(): Unit {
        throw Exception('TODO')
    }

    public func testToByteArrayFromString(): Unit {
        throw Exception('TODO')
    }

    public func testFromAsciiCharArray(): Unit {
        throw Exception('TODO')
    }

    public func testFromAsciiByteArray(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeByteArray(): Unit {
        throw Exception('TODO')
    }

    public func testToAsciiBytes(): Unit {
        throw Exception('TODO')
    }

    public func testToAsciiChars(): Unit {
        throw Exception('TODO')
    }

    public func testToAsciiString(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeObjectNull(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeObjectException(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeObject(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

