// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class CharSequenceUtilsTest {
    // Fields Begin
    static let TEST_DATA: Array<Any> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testRegionMatches(): Unit {
        throw Exception('TODO')
    }

    public func testConstructor(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

open class TestData {
    // Fields Begin
    let source: String = throw Exception('TODO')
    let ignoreCase: Bool = throw Exception('TODO')
    let toffset: Int64 = throw Exception('TODO')
    let other: String = throw Exception('TODO')
    let ooffset: Int64 = throw Exception('TODO')
    let len: Int64 = throw Exception('TODO')
    let expected: Bool = throw Exception('TODO')
    let throwable: Type<Any> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    init(source: String, ignoreCase: Bool, toffset: Int64, other: String, ooffset: Int64, len: Int64, expected: Bool) {
        throw Exception('TODO')
    }

    init(source: String, ignoreCase: Bool, toffset: Int64, other: String, ooffset: Int64, len: Int64, throwable: Type<Any>) {
        throw Exception('TODO')
    }

    public func toString(): String {
        throw Exception('TODO')
    }

    // Methods End
}

abstract open class RunTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    func invoke(): Bool {
        throw Exception('TODO')
    }

    func run(data: Any, id: String): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

