// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

open class Codec105ErrorInputStream <: InputStream {
    // Fields Begin
    static let EOF: Int64 = throw Exception('TODO')
    var countdown: Int64 = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public open func read(): Int64 {
        throw Exception('TODO')
    }

    public open func read(b: Int8, pos: Int64, len: Int64): Int64 {
        throw Exception('TODO')
    }

    // Methods End
}

