// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class StringUtilsTest {
    // Fields Begin
    static let BYTES_FIXTURE: Array<Int8> = throw Exception('TODO')
    static let BYTES_FIXTURE_16BE: Array<Int8> = throw Exception('TODO')
    static let BYTES_FIXTURE_16LE: Array<Int8> = throw Exception('TODO')
    static let STRING_FIXTURE: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testConstructor(): Unit {
        throw Exception('TODO')
    }

    public func testGetBytesIso8859_1(): Unit {
        throw Exception('TODO')
    }

    private func testGetBytesUnchecked(charsetName: String): Unit {
        throw Exception('TODO')
    }

    public func testGetBytesUsAscii(): Unit {
        throw Exception('TODO')
    }

    public func testGetBytesUtf16(): Unit {
        throw Exception('TODO')
    }

    public func testGetBytesUtf16Be(): Unit {
        throw Exception('TODO')
    }

    public func testGetBytesUtf16Le(): Unit {
        throw Exception('TODO')
    }

    public func testGetBytesUtf8(): Unit {
        throw Exception('TODO')
    }

    public func testGetBytesUncheckedBadName(): Unit {
        throw Exception('TODO')
    }

    public func testGetBytesUncheckedNullInput(): Unit {
        throw Exception('TODO')
    }

    private func testNewString(charsetName: String): Unit {
        throw Exception('TODO')
    }

    public func testNewStringBadEnc(): Unit {
        throw Exception('TODO')
    }

    public func testNewStringNullInput(): Unit {
        throw Exception('TODO')
    }

    public func testNewStringNullInput_CODEC229(): Unit {
        throw Exception('TODO')
    }

    public func testNewStringIso8859_1(): Unit {
        throw Exception('TODO')
    }

    public func testNewStringUsAscii(): Unit {
        throw Exception('TODO')
    }

    public func testNewStringUtf16(): Unit {
        throw Exception('TODO')
    }

    public func testNewStringUtf16Be(): Unit {
        throw Exception('TODO')
    }

    public func testNewStringUtf16Le(): Unit {
        throw Exception('TODO')
    }

    public func testNewStringUtf8(): Unit {
        throw Exception('TODO')
    }

    public func testEqualsString(): Unit {
        throw Exception('TODO')
    }

    public func testEqualsCS1(): Unit {
        throw Exception('TODO')
    }

    public func testEqualsCS2(): Unit {
        throw Exception('TODO')
    }

    public func testByteBufferUtf8(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

