// Package: commons_cli.bug
package commons_cli.bug

// Imports Begin
// Imports End

@Test
open class BugCLI71Test {
    // Fields Begin
    var options: Options = throw Exception('TODO')
    var parser: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testBasic(): Unit {
        throw Exception('TODO')
    }

    public func testGetsDefaultIfOptional(): Unit {
        throw Exception('TODO')
    }

    public func testLackOfError(): Unit {
        throw Exception('TODO')
    }

    public func testMistakenArgument(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

