// Package: commons_cli.bug
package commons_cli.bug

// Imports Begin
// Imports End

@Test
open class BugCLI265Test {
    // Fields Begin
    var parser: Any = throw Exception('TODO')
    var options: Options = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func shouldParseConcatenatedShortOptions(): Unit {
        throw Exception('TODO')
    }

    public func shouldParseShortOptionWithoutValue(): Unit {
        throw Exception('TODO')
    }

    public func shouldParseShortOptionWithValue(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

