// Package: commons_cli.bug
package commons_cli.bug

// Imports Begin
// Imports End

@Test
open class BugCLI148Test {
    // Fields Begin
    var options: Options = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testWorkaround1(): Unit {
        throw Exception('TODO')
    }

    public func testWorkaround2(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

