// Package: commons_cli.bug
package commons_cli.bug

// Imports Begin
// Imports End

@Test
open class BugCLI252Test {
    // Fields Begin
    // Fields End

    // Methods Begin
    private func getOptions(): Options {
        throw Exception('TODO')
    }

    public func testAmbiquousOptionName(): Unit {
        throw Exception('TODO')
    }

    public func testExactOptionNameMatch(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

