// Package: commons_cli.bug
package commons_cli.bug

// Imports Begin
// Imports End

@Test
open class BugsTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func test11456(): Unit {
        throw Exception('TODO')
    }

    public func test11457(): Unit {
        throw Exception('TODO')
    }

    public func test11458(): Unit {
        throw Exception('TODO')
    }

    public func test11680(): Unit {
        throw Exception('TODO')
    }

    public func test12210(): Unit {
        throw Exception('TODO')
    }

    public func test13425(): Unit {
        throw Exception('TODO')
    }

    public func test13666(): Unit {
        throw Exception('TODO')
    }

    public func test13935(): Unit {
        throw Exception('TODO')
    }

    public func test14786(): Unit {
        throw Exception('TODO')
    }

    public func test15046(): Unit {
        throw Exception('TODO')
    }

    public func test15648(): Unit {
        throw Exception('TODO')
    }

    public func test31148(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

