// Package: commons_codec.net
package commons_codec.net

// Imports Begin
// Imports End

@Test
open class PercentCodecTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testBasicEncodeDecode(): Unit {
        throw Exception('TODO')
    }

    public func testBasicSpace(): Unit {
        throw Exception('TODO')
    }

    public func testConfigurablePercentEncoder(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeInvalidEncodedResultDecoding(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeNullObject(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeUnsupportedObject(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeNullObject(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeUnsupportedObject(): Unit {
        throw Exception('TODO')
    }

    public func testPercentEncoderDecoderWithNullOrEmptyInput(): Unit {
        throw Exception('TODO')
    }

    public func testPercentEncoderDecoderWithPlusForSpace(): Unit {
        throw Exception('TODO')
    }

    public func testSafeCharEncodeDecodeObject(): Unit {
        throw Exception('TODO')
    }

    public func testUnsafeCharEncodeDecode(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

