// Package: commons_codec.net
package commons_codec.net

// Imports Begin
// Imports End

open class Utils {
    // Fields Begin
    static let RADIX: Int64 = throw Exception('TODO')
    // Fields End

    // Methods Begin
    static func digit16(b: Int8): Int64 {
        throw Exception('TODO')
    }

    static func hexDigit(b: Int64): Rune {
        throw Exception('TODO')
    }

    // Methods End
}

