// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

@Test
open class BeiderMorseEncoderTest {
    // Fields Begin
    static let TEST_CHARS: Array<Rune> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private func assertNotEmpty(bmpm: Any, value: String): Unit {
        throw Exception('TODO')
    }

    private func createGenericApproxEncoder(): Any {
        throw Exception('TODO')
    }

    protected func createStringEncoder(): Any {
        throw Exception('TODO')
    }

    public func testAllChars(): Unit {
        throw Exception('TODO')
    }

    public func testAsciiEncodeNotEmpty1Letter(): Unit {
        throw Exception('TODO')
    }

    public func testAsciiEncodeNotEmpty2Letters(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeAtzNotEmpty(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeGna(): Unit {
        throw Exception('TODO')
    }

    public func testInvalidLangIllegalArgumentException(): Unit {
        throw Exception('TODO')
    }

    public func testInvalidLangIllegalStateException(): Unit {
        throw Exception('TODO')
    }

    public func testInvalidLanguageIllegalArgumentException(): Unit {
        throw Exception('TODO')
    }

    public func testLongestEnglishSurname(): Unit {
        throw Exception('TODO')
    }

    public func testNegativeIndexForRuleMatchIndexOutOfBoundsException(): Unit {
        throw Exception('TODO')
    }

    public func testOOM(): Unit {
        throw Exception('TODO')
    }

    public func testSetConcat(): Unit {
        throw Exception('TODO')
    }

    public func testSetNameTypeAsh(): Unit {
        throw Exception('TODO')
    }

    public func testSetRuleTypeExact(): Unit {
        throw Exception('TODO')
    }

    public func testSetRuleTypeToRulesIllegalArgumentException(): Unit {
        throw Exception('TODO')
    }

    public func testSpeedCheck(): Unit {
        throw Exception('TODO')
    }

    public func testSpeedCheck2(): Unit {
        throw Exception('TODO')
    }

    public func testSpeedCheck3(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

