// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

@Test
open class CacheSubSequencePerformanceTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public open func test(): Unit {
        throw Exception('TODO')
    }

    private open func test(input: Any, times: Int64): Unit {
        throw Exception('TODO')
    }

    private open func test(input: Any): Unit {
        throw Exception('TODO')
    }

    private func cacheSubSequence(cached: Any): Any {
        throw Exception('TODO')
    }

    // Methods End
}

