// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

@Test
open class LanguageGuessingTest {
    // Fields Begin
    let lang: Any = throw Exception('TODO')
    let language: String = throw Exception('TODO')
    let name: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public static func data(): ArrayList<Array<Any>> {
        throw Exception('TODO')
    }

    public init(name: String, language: String) {
        throw Exception('TODO')
    }

    public func testLanguageGuessing(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

