// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

@Test
open class PhoneticEngineRegressionTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testSolrGENERIC(): Unit {
        throw Exception('TODO')
    }

    public func testSolrASHKENAZI(): Unit {
        throw Exception('TODO')
    }

    public func testSolrSEPHARDIC(): Unit {
        throw Exception('TODO')
    }

    public func testCompatibilityWithOriginalVersion(): Unit {
        throw Exception('TODO')
    }

    private static func encode(args: HashMap<String, String>, concat: Bool, input: String): String {
        throw Exception('TODO')
    }

    // Methods End
}

