// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

open class ResourceConstants {
    // Fields Begin
    static let CMT: String = throw Exception('TODO')
    static let ENCODING: String = throw Exception('TODO')
    static let EXT_CMT_END: String = throw Exception('TODO')
    static let EXT_CMT_START: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    // Methods End
}

