// Package: commons_codec.bm
package commons_codec.bm

// Imports Begin
// Imports End

@Test
open class RuleTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    private func makePhonemes(): Array<Array<Any>> {
        throw Exception('TODO')
    }

    public func testPhonemeComparedToSelfIsZero(): Unit {
        throw Exception('TODO')
    }

    public func testSubSequenceWorks(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

