// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class ApplicationTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testAnt(): Unit {
        throw Exception('TODO')
    }

    public func testGroovy(): Unit {
        throw Exception('TODO')
    }

    public func testLs(): Unit {
        throw Exception('TODO')
    }

    public func testMan(): Unit {
        throw Exception('TODO')
    }

    public func testNLT(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

