// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class BasicParserTest <: ParserTestCase {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testAmbiguousLongWithoutEqualSingleDash(): Unit {
        throw Exception('TODO')
    }

    public func testAmbiguousPartialLongOption1(): Unit {
        throw Exception('TODO')
    }

    public func testAmbiguousPartialLongOption2(): Unit {
        throw Exception('TODO')
    }

    public func testAmbiguousPartialLongOption3(): Unit {
        throw Exception('TODO')
    }

    public func testAmbiguousPartialLongOption4(): Unit {
        throw Exception('TODO')
    }

    public func testBursting(): Unit {
        throw Exception('TODO')
    }

    public func testDoubleDash2(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionWithEqualsQuoteHandling(): Unit {
        throw Exception('TODO')
    }

    public func testLongWithEqualDoubleDash(): Unit {
        throw Exception('TODO')
    }

    public func testLongWithEqualSingleDash(): Unit {
        throw Exception('TODO')
    }

    public func testLongWithoutEqualSingleDash(): Unit {
        throw Exception('TODO')
    }

    public func testMissingArgWithBursting(): Unit {
        throw Exception('TODO')
    }

    public func testNegativeOption(): Unit {
        throw Exception('TODO')
    }

    public func testPartialLongOptionSingleDash(): Unit {
        throw Exception('TODO')
    }

    public func testPropertiesOption1(): Unit {
        throw Exception('TODO')
    }

    public func testPropertiesOption2(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionConcatenatedQuoteHandling(): Unit {
        throw Exception('TODO')
    }

    public func testShortWithEqual(): Unit {
        throw Exception('TODO')
    }

    public func testShortWithoutEqual(): Unit {
        throw Exception('TODO')
    }

    public func testStopBursting(): Unit {
        throw Exception('TODO')
    }

    public func testStopBursting2(): Unit {
        throw Exception('TODO')
    }

    public func testUnambiguousPartialLongOption1(): Unit {
        throw Exception('TODO')
    }

    public func testUnambiguousPartialLongOption2(): Unit {
        throw Exception('TODO')
    }

    public func testUnambiguousPartialLongOption3(): Unit {
        throw Exception('TODO')
    }

    public func testUnambiguousPartialLongOption4(): Unit {
        throw Exception('TODO')
    }

    public func testUnrecognizedOptionWithBursting(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

