// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class CommandLineTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testBuilder(): Unit {
        throw Exception('TODO')
    }

    public func testGetOptionProperties(): Unit {
        throw Exception('TODO')
    }

    public func testGetOptionPropertiesWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testGetOptions(): Unit {
        throw Exception('TODO')
    }

    public func testGetParsedOptionValue(): Unit {
        throw Exception('TODO')
    }

    public func testGetParsedOptionValueWithChar(): Unit {
        throw Exception('TODO')
    }

    public func testGetParsedOptionValueWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testNullhOption(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

