// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class DefaultParserTest <: ParserTestCase {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testBuilder(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionQuoteHandlingWithoutStrip(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionQuoteHandlingWithStrip(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionWithEqualsQuoteHandling(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionWithEqualsQuoteHandlingWithoutStrip(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionWithEqualsQuoteHandlingWithStrip(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionConcatenatedQuoteHandling(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionQuoteHandlingWithoutStrip(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionQuoteHandlingWithStrip(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

