// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class OptionBuilderTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testBaseOptionCharOpt(): Unit {
        throw Exception('TODO')
    }

    public func testBaseOptionStringOpt(): Unit {
        throw Exception('TODO')
    }

    public func testBuilderIsResettedAlways(): Unit {
        throw Exception('TODO')
    }

    public func testCompleteOption(): Unit {
        throw Exception('TODO')
    }

    public func testCreateIncompleteOption(): Unit {
        throw Exception('TODO')
    }

    public func testIllegalOptions(): Unit {
        throw Exception('TODO')
    }

    public func testOptionArgNumbers(): Unit {
        throw Exception('TODO')
    }

    public func testSpecialOptChars(): Unit {
        throw Exception('TODO')
    }

    public func testTwoCompleteOptions(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

