// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class OptionGroupTest {
    // Fields Begin
    var options: Options = throw Exception('TODO')
    let parser: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testGetNames(): Unit {
        throw Exception('TODO')
    }

    public func testNoOptionsExtraArgs(): Unit {
        throw Exception('TODO')
    }

    public func testSingleLongOption(): Unit {
        throw Exception('TODO')
    }

    public func testSingleOption(): Unit {
        throw Exception('TODO')
    }

    public func testSingleOptionFromGroup(): Unit {
        throw Exception('TODO')
    }

    public func testToString(): Unit {
        throw Exception('TODO')
    }

    public func testTwoLongOptionsFromGroup(): Unit {
        throw Exception('TODO')
    }

    public func testTwoOptionsFromDifferentGroup(): Unit {
        throw Exception('TODO')
    }

    public func testTwoOptionsFromGroup(): Unit {
        throw Exception('TODO')
    }

    public func testTwoOptionsFromGroupWithProperties(): Unit {
        throw Exception('TODO')
    }

    public func testTwoValidLongOptions(): Unit {
        throw Exception('TODO')
    }

    public func testTwoValidOptions(): Unit {
        throw Exception('TODO')
    }

    public func testValidLongOnlyOptions(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

