// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class TypeHandlerTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testCreateValueClass(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueClass_notFound(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueDate(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueExistingFile(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueExistingFile_nonExistingFile(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueFile(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueFiles(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueInteger_failure(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueNumber_Double(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueNumber_Long(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueNumber_noNumber(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueObject_InstantiableClass(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueObject_notInstantiableClass(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueObject_unknownClass(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueString(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueURL(): Unit {
        throw Exception('TODO')
    }

    public func testCreateValueURL_malformed(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

open class Instantiable {
    // Fields Begin
    // Fields End

    // Methods Begin
    // Methods End
}

class NotInstantiable {
    // Fields Begin
    // Fields End

    // Methods Begin
    private init() {
        throw Exception('TODO')
    }

    // Methods End
}

