// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

open class TypeHandler {
    // Fields Begin
    // Fields End

    // Methods Begin
    public static func createClass(classname: String): Type<Any> {
        throw Exception('TODO')
    }

    public static func createDate(str: String): Any {
        throw Exception('TODO')
    }

    public static func createFile(str: String): Any {
        throw Exception('TODO')
    }

    public static func createFiles(str: String): Array<Any> {
        throw Exception('TODO')
    }

    public static func createNumber(str: String): Number {
        throw Exception('TODO')
    }

    public static func createObject(classname: String): Any {
        throw Exception('TODO')
    }

    public static func createURL(str: String): Any {
        throw Exception('TODO')
    }

    public static func createValue(str: String, clazz: Type<Any>): <Any> {
        throw Exception('TODO')
    }

    public static func createValue(str: String, obj: Any): Any {
        throw Exception('TODO')
    }

    public static func openFile(str: String): Any {
        throw Exception('TODO')
    }

    // Methods End
}

