// Package: HashMapTest
package HashMapTest

// Imports Begin
import HashMapTest.runtime.AnyHashable
import std.collection.HashMap
// Imports End

public open class HashMapTest {
    // Fields Begin
    var map: HashMap<AnyHashable, String> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public open func testHashMap(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

