// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class ArgumentIsOptionTest {
    // Fields Begin
    var options: Options = throw Exception('TODO')
    var parser: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testOption(): Unit {
        throw Exception('TODO')
    }

    public func testOptionAndOptionWithArgument(): Unit {
        throw Exception('TODO')
    }

    public func testOptionWithArgument(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

