// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class HelpFormatterTest {
    // Fields Begin
    static let EOL: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testAccessors(): Unit {
        throw Exception('TODO')
    }

    public func testAutomaticUsage(): Unit {
        throw Exception('TODO')
    }

    public func testDefaultArgName(): Unit {
        throw Exception('TODO')
    }

    public func testFindWrapPos(): Unit {
        throw Exception('TODO')
    }

    public func testHeaderStartingWithLineSeparator(): Unit {
        throw Exception('TODO')
    }

    public func testHelpWithLongOptSeparator(): Unit {
        throw Exception('TODO')
    }

    public func testIndentedHeaderAndFooter(): Unit {
        throw Exception('TODO')
    }

    public func testOptionWithoutShortFormat(): Unit {
        throw Exception('TODO')
    }

    public func testOptionWithoutShortFormat2(): Unit {
        throw Exception('TODO')
    }

    public func testPrintHelpNewlineFooter(): Unit {
        throw Exception('TODO')
    }

    public func testPrintHelpNewlineHeader(): Unit {
        throw Exception('TODO')
    }

    public func testPrintHelpWithEmptySyntax(): Unit {
        throw Exception('TODO')
    }

    public func testPrintOptionGroupUsage(): Unit {
        throw Exception('TODO')
    }

    public func testPrintOptions(): Unit {
        throw Exception('TODO')
    }

    public func testPrintOptionWithEmptyArgNameUsage(): Unit {
        throw Exception('TODO')
    }

    public func testPrintRequiredOptionGroupUsage(): Unit {
        throw Exception('TODO')
    }

    public func testPrintSortedUsage(): Unit {
        throw Exception('TODO')
    }

    public func testPrintSortedUsageWithNullComparator(): Unit {
        throw Exception('TODO')
    }

    public func testPrintUsage(): Unit {
        throw Exception('TODO')
    }

    public func testRenderWrappedTextMultiLine(): Unit {
        throw Exception('TODO')
    }

    public func testRenderWrappedTextMultiLinePadded(): Unit {
        throw Exception('TODO')
    }

    public func testRenderWrappedTextSingleLine(): Unit {
        throw Exception('TODO')
    }

    public func testRenderWrappedTextSingleLinePadded(): Unit {
        throw Exception('TODO')
    }

    public func testRenderWrappedTextSingleLinePadded2(): Unit {
        throw Exception('TODO')
    }

    public func testRenderWrappedTextWordCut(): Unit {
        throw Exception('TODO')
    }

    public func testRtrim(): Unit {
        throw Exception('TODO')
    }

    public func testUsageWithLongOptSeparator(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

