// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

class OptionValidator {
    // Fields Begin
    // Fields End

    // Methods Begin
    private static func isValidChar(c: Rune): Bool {
        throw Exception('TODO')
    }

    private static func isValidOpt(c: Rune): Bool {
        throw Exception('TODO')
    }

    static func validate(option: String): String {
        throw Exception('TODO')
    }

    // Methods End
}

