// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class OptionsTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testDuplicateLong(): Unit {
        throw Exception('TODO')
    }

    public func testDuplicateSimple(): Unit {
        throw Exception('TODO')
    }

    public func testGetMatchingOpts(): Unit {
        throw Exception('TODO')
    }

    public func testGetOptionsGroups(): Unit {
        throw Exception('TODO')
    }

    public func testHelpOptions(): Unit {
        throw Exception('TODO')
    }

    public func testLong(): Unit {
        throw Exception('TODO')
    }

    public func testMissingOptionException(): Unit {
        throw Exception('TODO')
    }

    public func testMissingOptionsException(): Unit {
        throw Exception('TODO')
    }

    public func testSimple(): Unit {
        throw Exception('TODO')
    }

    public func testToString(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

