// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class PatternOptionBuilderTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testClassPattern(): Unit {
        throw Exception('TODO')
    }

    public func testEmptyPattern(): Unit {
        throw Exception('TODO')
    }

    public func testExistingFilePattern(): Unit {
        throw Exception('TODO')
    }

    public func testExistingFilePatternFileNotExist(): Unit {
        throw Exception('TODO')
    }

    public func testNumberPattern(): Unit {
        throw Exception('TODO')
    }

    public func testObjectPattern(): Unit {
        throw Exception('TODO')
    }

    public func testRequiredOption(): Unit {
        throw Exception('TODO')
    }

    public func testSimplePattern(): Unit {
        throw Exception('TODO')
    }

    public func testUntypedPattern(): Unit {
        throw Exception('TODO')
    }

    public func testURLPattern(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

