// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class PosixParserTest <: ParserTestCase {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testAmbiguousLongWithoutEqualSingleDash(): Unit {
        throw Exception('TODO')
    }

    public func testAmbiguousPartialLongOption4(): Unit {
        throw Exception('TODO')
    }

    public func testDoubleDash2(): Unit {
        throw Exception('TODO')
    }

    public func testLongWithEqualSingleDash(): Unit {
        throw Exception('TODO')
    }

    public func testLongWithoutEqualSingleDash(): Unit {
        throw Exception('TODO')
    }

    public func testLongWithUnexpectedArgument1(): Unit {
        throw Exception('TODO')
    }

    public func testNegativeOption(): Unit {
        throw Exception('TODO')
    }

    public func testShortWithEqual(): Unit {
        throw Exception('TODO')
    }

    public func testUnambiguousPartialLongOption4(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

