// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class ValuesTest {
    // Fields Begin
    var cmd: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testCharSeparator(): Unit {
        throw Exception('TODO')
    }

    public func testComplexValues(): Unit {
        throw Exception('TODO')
    }

    public func testExtraArgs(): Unit {
        throw Exception('TODO')
    }

    public func testMultipleArgValues(): Unit {
        throw Exception('TODO')
    }

    public func testShortArgs(): Unit {
        throw Exception('TODO')
    }

    public func testShortArgsWithValue(): Unit {
        throw Exception('TODO')
    }

    public func testTwoArgValues(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

