// Package: commons_cli
package commons_cli

// Imports Begin
// Imports End

@Test
open class ValueTest {
    // Fields Begin
    var cl: Any = throw Exception('TODO')
    let opts: Options = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func testLongNoArg(): Unit {
        throw Exception('TODO')
    }

    public func testLongNoArgWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionalArgValue(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionalArgValues(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionalArgValuesWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionalArgValueWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionalNArgValues(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionalNArgValuesWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionalNoValue(): Unit {
        throw Exception('TODO')
    }

    public func testLongOptionalNoValueWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testLongWithArg(): Unit {
        throw Exception('TODO')
    }

    public func testLongWithArgWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testShortNoArg(): Unit {
        throw Exception('TODO')
    }

    public func testShortNoArgWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionalArgNoValue(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionalArgNoValueWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionalArgValue(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionalArgValues(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionalArgValuesWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionalArgValueWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionalNArgValues(): Unit {
        throw Exception('TODO')
    }

    public func testShortOptionalNArgValuesWithOption(): Unit {
        throw Exception('TODO')
    }

    public func testShortWithArg(): Unit {
        throw Exception('TODO')
    }

    public func testShortWithArgWithOption(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

