// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

open class MessageDigestAlgorithms {
    // Fields Begin
    static let SHA_512_224: String = throw Exception('TODO')
    static let SHA_512_256: String = throw Exception('TODO')
    static let SHA3_224: String = throw Exception('TODO')
    static let SHA3_256: String = throw Exception('TODO')
    static let SHA3_384: String = throw Exception('TODO')
    static let SHA3_512: String = throw Exception('TODO')
    static let MD2: String = throw Exception('TODO')
    static let MD5: String = throw Exception('TODO')
    static let SHA_1: String = throw Exception('TODO')
    static let SHA_224: String = throw Exception('TODO')
    static let SHA_256: String = throw Exception('TODO')
    static let SHA_384: String = throw Exception('TODO')
    static let SHA_512: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public static func values(): Array<String> {
        throw Exception('TODO')
    }

    private init() {
        throw Exception('TODO')
    }

    // Methods End
}

