// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

open class Sha2Crypt {
    // Fields Begin
    static let ROUNDS_DEFAULT: Int64 = throw Exception('TODO')
    static let ROUNDS_MAX: Int64 = throw Exception('TODO')
    static let ROUNDS_MIN: Int64 = throw Exception('TODO')
    static let ROUNDS_PREFIX: String = throw Exception('TODO')
    static let SHA256_BLOCKSIZE: Int64 = throw Exception('TODO')
    static let SHA256_PREFIX: String = throw Exception('TODO')
    static let SHA512_BLOCKSIZE: Int64 = throw Exception('TODO')
    static let SHA512_PREFIX: String = throw Exception('TODO')
    static let SALT_PATTERN: Regex = throw Exception('TODO')
    // Fields End

    // Methods Begin
    // Methods End
}

