// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

@Test
open class UnixCryptTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testCtor(): Unit {
        throw Exception('TODO')
    }

    public func testUnixCryptExplicitCall(): Unit {
        throw Exception('TODO')
    }

    public func testUnixCryptWithHalfSalt(): Unit {
        throw Exception('TODO')
    }

    public func testUnicCryptInvalidSalt(): Unit {
        throw Exception('TODO')
    }

    public func testUnixCryptNullData(): Unit {
        throw Exception('TODO')
    }

    public func testUnixCryptWithEmptySalt(): Unit {
        throw Exception('TODO')
    }

    public func testUnixCryptWithoutSalt(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

