// Package: commons_cli
package commons_cli

// Imports Begin

// Imports End

public open class PatternOptionBuilder {
    // Fields Begin
    static let STRING_VALUE: String = throw Exception('TODO')  // Already translated, compilation failed
    static let OBJECT_VALUE: Any = Object()  // Already translated, compilation failed
    static let NUMBER_VALUE: Any = throw Exception('TODO')  // Already translated, compilation failed
    static let DATE_VALUE: Any = throw Exception('TODO')  // Already translated, compilation failed
    static let CLASS_VALUE: Any = throw Exception('TODO')  // Already translated, compilation failed
    static let EXISTING_FILE_VALUE: Any = throw Exception('TODO')  // Already translated, compilation failed
    static let FILE_VALUE: Any = throw Exception('TODO')  // Already translated, compilation failed
    static let FILES_VALUE: Any = throw Exception('TODO')  // Already translated, compilation failed
    static let URL_VALUE: Any = throw Exception('TODO')  // Already translated, compilation failed
    // Fields End

    // Methods Begin
    public static func getValueClass(ch: Rune): Any {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    public static func isValueCode(ch: Rune): Bool {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    public static func parsePattern(pattern: String): Options {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    // Methods End
}

