// Package: commons_cli
package commons_cli

// Imports Begin

// Imports End

class Util {
    // Fields Begin
    static let EMPTY_STRING_ARRAY: Array<Any> = []
    // Fields End

    // Methods Begin
    static func stripLeadingAndTrailingQuotes(str: String): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    static func stripLeadingHyphens(str: String): String {
        throw Exception('TODO')  // Already translated, compilation failed
    }

    // Methods End
}

