// Package: commons_codec.net
package commons_codec.net

// Imports Begin
// Imports End

@Test
open class BCodecTest {
    // Fields Begin
    static let BASE64_IMPOSSIBLE_CASES: Array<String> = throw Exception('TODO')
    static let SWISS_GERMAN_STUFF_UNICODE: Int64 = throw Exception('TODO')
    static let RUSSIAN_STUFF_UNICODE: Int64 = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private func constructString(unicodeChars: Array<Int64>): String {
        throw Exception('TODO')
    }

    public func testNullInput(): Unit {
        throw Exception('TODO')
    }

    public func testUTF8RoundTrip(): Unit {
        throw Exception('TODO')
    }

    public func testBasicEncodeDecode(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeDecodeNull(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeStringWithNull(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeStringWithNull(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeObjects(): Unit {
        throw Exception('TODO')
    }

    public func testInvalidEncoding(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeObjects(): Unit {
        throw Exception('TODO')
    }

    public func testBase64ImpossibleSamplesDefault(): Unit {
        throw Exception('TODO')
    }

    public func testBase64ImpossibleSamplesLenient(): Unit {
        throw Exception('TODO')
    }

    public func testBase64ImpossibleSamplesStrict(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

