// Package: commons_codec.net
package commons_codec.net

// Imports Begin
// Imports End

@Test
open class QuotedPrintableCodecTest {
    // Fields Begin
    static let SWISS_GERMAN_STUFF_UNICODE: Int64 = throw Exception('TODO')
    static let RUSSIAN_STUFF_UNICODE: Int64 = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private func constructString(unicodeChars: Array<Int64>): String {
        throw Exception('TODO')
    }

    public func testUTF8RoundTrip(): Unit {
        throw Exception('TODO')
    }

    public func testBasicEncodeDecode(): Unit {
        throw Exception('TODO')
    }

    public func testSafeCharEncodeDecode(): Unit {
        throw Exception('TODO')
    }

    public func testUnsafeEncodeDecode(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeDecodeNull(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeInvalid(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeNull(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeUrlWithNullBitSet(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeWithNullArray(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeStringWithNull(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeStringWithNull(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeObjects(): Unit {
        throw Exception('TODO')
    }

    public func testInvalidEncoding(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeObjects(): Unit {
        throw Exception('TODO')
    }

    public func testDefaultEncoding(): Unit {
        throw Exception('TODO')
    }

    public func testSoftLineBreakDecode(): Unit {
        throw Exception('TODO')
    }

    public func testSoftLineBreakEncode(): Unit {
        throw Exception('TODO')
    }

    public func testSkipNotEncodedCRLF(): Unit {
        throw Exception('TODO')
    }

    public func testTrailingSpecial(): Unit {
        throw Exception('TODO')
    }

    public func testUltimateSoftBreak(): Unit {
        throw Exception('TODO')
    }

    public func testFinalBytes(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

