// Package: commons_codec.net
package commons_codec.net

// Imports Begin
// Imports End

@Test
open class RFC1522CodecTest {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func testNullInput(): Unit {
        throw Exception('TODO')
    }

    private func assertExpectedDecoderException(s: String): Unit {
        throw Exception('TODO')
    }

    public func testDecodeInvalid(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

open class RFC1522TestCodec <: RFC1522Codec {
    // Fields Begin
    // Fields End

    // Methods Begin
    protected func doDecoding(bytes: Array<Int8>): Array<Int8> {
        throw Exception('TODO')
    }

    protected func doEncoding(bytes: Array<Int8>): Array<Int8> {
        throw Exception('TODO')
    }

    protected func getEncoding(): String {
        throw Exception('TODO')
    }

    // Methods End
}

