// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

open class Base64TestData {
    // Fields Begin
    static let CODEC_101_INPUT_LENGTH_IS_MULTIPLE_OF_3: String = throw Exception('TODO')
    static let CODEC_98_NPE: String = throw Exception('TODO')
    static let CODEC_98_NPE_DECODED: String = throw Exception('TODO')
    static let ENCODED_64_CHARS_PER_LINE: String = throw Exception('TODO')
    static let ENCODED_76_CHARS_PER_LINE: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    // Methods End
}

