// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class Base16Test {
    // Fields Begin
    static let CHARSET_UTF8: Any = throw Exception('TODO')
    let random: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func getRandom(): Any {
        throw Exception('TODO')
    }

    public func testBase16(): Unit {
        throw Exception('TODO')
    }

    public func testCodec68(): Unit {
        throw Exception('TODO')
    }

    public func testConstructors(): Unit {
        throw Exception('TODO')
    }

    public func testConstructor_LowerCase(): Unit {
        throw Exception('TODO')
    }

    public func testConstructor_LowerCase_DecodingPolicy(): Unit {
        throw Exception('TODO')
    }

    public func testEmptyBase16(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeDecodeRandom(): Unit {
        throw Exception('TODO')
    }

    public func testEncodeDecodeSmall(): Unit {
        throw Exception('TODO')
    }

    public func testKnownDecodings(): Unit {
        throw Exception('TODO')
    }

    public func testKnownEncodings(): Unit {
        throw Exception('TODO')
    }

    public func testNonBase16Test(): Unit {
        throw Exception('TODO')
    }

    public func testObjectDecodeWithInvalidParameter(): Unit {
        throw Exception('TODO')
    }

    public func testObjectDecodeWithValidParameter(): Unit {
        throw Exception('TODO')
    }

    public func testObjectEncodeWithInvalidParameter(): Unit {
        throw Exception('TODO')
    }

    public func testObjectEncodeWithValidParameter(): Unit {
        throw Exception('TODO')
    }

    public func testObjectEncode(): Unit {
        throw Exception('TODO')
    }

    public func testPairs(): Unit {
        throw Exception('TODO')
    }

    public func testSingletons(): Unit {
        throw Exception('TODO')
    }

    public func testTriplets(): Unit {
        throw Exception('TODO')
    }

    public func testByteToStringVariations(): Unit {
        throw Exception('TODO')
    }

    public func testStringToByteVariations(): Unit {
        throw Exception('TODO')
    }

    private func toString(data: Array<Int8>): String {
        throw Exception('TODO')
    }

    public func checkEncodeLengthBounds(): Unit {
        throw Exception('TODO')
    }

    public func testIsInAlphabet(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeSingleBytes(): Unit {
        throw Exception('TODO')
    }

    public func testDecodeSingleBytesOptimisation(): Unit {
        throw Exception('TODO')
    }

    public func testStrictDecoding(): Unit {
        throw Exception('TODO')
    }

    public func testLenientDecoding(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

