// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class Base32OutputStreamTest {
    // Fields Begin
    static let CR_LF: Array<Int8> = throw Exception('TODO')
    static let LF: Array<Int8> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testBase32EmptyOutputStreamMimeChunkSize(): Unit {
        throw Exception('TODO')
    }

    public func testBase32EmptyOutputStreamPemChunkSize(): Unit {
        throw Exception('TODO')
    }

    private func testBase32EmptyOutputStream(chunkSize: Int64): Unit {
        throw Exception('TODO')
    }

    public func testBase32OutputStreamByChunk(): Unit {
        throw Exception('TODO')
    }

    public func testBase32OutputStreamByteByByte(): Unit {
        throw Exception('TODO')
    }

    private func testByChunk(encoded: Array<Int8>, decoded: Array<Int8>, chunkSize: Int64, separator: Array<Int8>): Unit {
        throw Exception('TODO')
    }

    private func testByteByByte(encoded: Array<Int8>, decoded: Array<Int8>, chunkSize: Int64, separator: Array<Int8>): Unit {
        throw Exception('TODO')
    }

    public func testWriteOutOfBounds(): Unit {
        throw Exception('TODO')
    }

    public func testWriteToNullCoverage(): Unit {
        throw Exception('TODO')
    }

    public func testStrictDecoding(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

