// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class Base16InputStreamTest {
    // Fields Begin
    static let ENCODED_B16: String = throw Exception('TODO')
    static let STRING_FIXTURE: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testAvailable(): Unit {
        throw Exception('TODO')
    }

    public func testBase16EmptyInputStream(): Unit {
        throw Exception('TODO')
    }

    public func testBase16InputStreamByChunk(): Unit {
        throw Exception('TODO')
    }

    public func testBase16InputStreamByteByByte(): Unit {
        throw Exception('TODO')
    }

    private open func testByChunk(encoded: Array<Int8>, decoded: Array<Int8>): Unit {
        throw Exception('TODO')
    }

    private open func testByChunk(encoded: Array<Int8>, decoded: Array<Int8>, lowerCase: Bool): Unit {
        throw Exception('TODO')
    }

    private open func testByteByByte(encoded: Array<Int8>, decoded: Array<Int8>): Unit {
        throw Exception('TODO')
    }

    private open func testByteByByte(encoded: Array<Int8>, decoded: Array<Int8>, lowerCase: Bool): Unit {
        throw Exception('TODO')
    }

    public func testMarkSupported(): Unit {
        throw Exception('TODO')
    }

    public func testRead0(): Unit {
        throw Exception('TODO')
    }

    public func testReadNull(): Unit {
        throw Exception('TODO')
    }

    public func testReadOutOfBounds(): Unit {
        throw Exception('TODO')
    }

    public func testSkipBig(): Unit {
        throw Exception('TODO')
    }

    public func testSkipNone(): Unit {
        throw Exception('TODO')
    }

    public func testSkipPastEnd(): Unit {
        throw Exception('TODO')
    }

    public func testSkipToEnd(): Unit {
        throw Exception('TODO')
    }

    public func testSkipWrongArgument(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

