// Package: commons_codec.binary
package commons_codec.binary

// Imports Begin
// Imports End

@Test
open class Base64Codec13Test {
    // Fields Begin
    static let STRINGS: Array<String> = throw Exception('TODO')
    static let CHUNKED_STRINGS: Array<String> = throw Exception('TODO')
    static let BYTES: Array<Array<Int8>> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    private static func initSTRINGS(): Unit {
        throw Exception('TODO')
    }

    private static func initCHUNKED_STRINGS(): Unit {
        throw Exception('TODO')
    }

    private static func initBYTES(): Unit {
        throw Exception('TODO')
    }

    public func testEncoder(): Unit {
        throw Exception('TODO')
    }

    public func testDecoder(): Unit {
        throw Exception('TODO')
    }

    public func testBinaryEncoder(): Unit {
        throw Exception('TODO')
    }

    public func testBinaryDecoder(): Unit {
        throw Exception('TODO')
    }

    public func testStaticEncode(): Unit {
        throw Exception('TODO')
    }

    public func testStaticDecode(): Unit {
        throw Exception('TODO')
    }

    public func testStaticEncodeChunked(): Unit {
        throw Exception('TODO')
    }

    public func testStaticDecodeChunked(): Unit {
        throw Exception('TODO')
    }

    private static func utf8(s: String): Array<Int8> {
        throw Exception('TODO')
    }

    // Methods End
}

