/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 19:04:17 GMT 2025
 */

package org.apache.commons.codec.language.bm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import java.util.LinkedHashSet;
import java.util.Set;
import org.apache.commons.codec.language.bm.Languages;
import org.apache.commons.codec.language.bm.PhoneticEngine;
import org.apache.commons.codec.language.bm.Rule;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PhoneticEngine$PhonemeBuilder_ESTest extends PhoneticEngine$PhonemeBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedHashSet<Rule.Rule_Phoneme> linkedHashSet0 = new LinkedHashSet<Rule.Rule_Phoneme>();
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = new PhoneticEngine.PhoneticEngine_PhonemeBuilder((-352), linkedHashSet0, (Rule.Rule_Phoneme) null);
      // Undeclared exception!
      try { 
        phoneticEngine_PhonemeBuilder0.makeString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.codec.language.bm.PhoneticEngine$PhoneticEngine_PhonemeBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty((Languages.Languages_LanguageSet) null);
      Rule.Rule_Phoneme rule_Phoneme0 = new Rule.Rule_Phoneme(32, "", (Languages.Languages_LanguageSet) null, (Rule.Rule_Phoneme) null);
      // Undeclared exception!
      try { 
        phoneticEngine_PhonemeBuilder0.apply(rule_Phoneme0, 32);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.codec.language.bm.PhoneticEngine$PhoneticEngine_PhonemeBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty((Languages.Languages_LanguageSet) null);
      // Undeclared exception!
      try { 
        phoneticEngine_PhonemeBuilder0.apply((Rule.Rule_PhonemeExpr) null, (-3143));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal initial capacity: -3143
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("");
      Languages.Languages_LanguageSet languages_LanguageSet0 = Languages.Languages_LanguageSet.from(linkedHashSet0);
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty(languages_LanguageSet0);
      Languages.Languages_NoLanguage languages_NoLanguage0 = new Languages.Languages_NoLanguage();
      Rule.Rule_Phoneme rule_Phoneme0 = mock(Rule.Rule_Phoneme.class, new ViolatedAssumptionAnswer());
      Rule.Rule_Phoneme rule_Phoneme1 = new Rule.Rule_Phoneme(836, "", languages_NoLanguage0, rule_Phoneme0);
      // Undeclared exception!
      try { 
        phoneticEngine_PhonemeBuilder0.apply(rule_Phoneme1, 836);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class org.apache.commons.codec.language.bm.Languages$Languages_NoLanguage cannot be cast to class org.apache.commons.codec.language.bm.Languages$SomeLanguages (org.apache.commons.codec.language.bm.Languages$Languages_NoLanguage and org.apache.commons.codec.language.bm.Languages$SomeLanguages are in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @5294c8c4)
         //
         verifyException("org.apache.commons.codec.language.bm.Languages$SomeLanguages", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Languages.Languages_AnyLanguage languages_AnyLanguage0 = new Languages.Languages_AnyLanguage();
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty(languages_AnyLanguage0);
      Set<Rule.Rule_Phoneme> set0 = phoneticEngine_PhonemeBuilder0.getPhonemes();
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder1 = new PhoneticEngine.PhoneticEngine_PhonemeBuilder(6, set0, (Rule.Rule_Phoneme) null);
      CharBuffer charBuffer0 = CharBuffer.allocate(2);
      // Undeclared exception!
      try { 
        phoneticEngine_PhonemeBuilder1.append(charBuffer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.codec.language.bm.PhoneticEngine$PhoneticEngine_PhonemeBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Languages.Languages_LanguageSet languages_LanguageSet0 = Languages.Languages_LanguageSet.from(linkedHashSet0);
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty(languages_LanguageSet0);
      String string0 = phoneticEngine_PhonemeBuilder0.makeString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("");
      Languages.Languages_LanguageSet languages_LanguageSet0 = Languages.Languages_LanguageSet.from(linkedHashSet0);
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty(languages_LanguageSet0);
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0, 2, 1);
      Rule.Rule_Phoneme rule_Phoneme0 = mock(Rule.Rule_Phoneme.class, new ViolatedAssumptionAnswer());
      Rule.Rule_Phoneme rule_Phoneme1 = new Rule.Rule_Phoneme(2, charBuffer0, languages_LanguageSet0, rule_Phoneme0);
      phoneticEngine_PhonemeBuilder0.apply(rule_Phoneme1, 279);
      assertFalse(rule_Phoneme1.equals((Object)rule_Phoneme0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("");
      Languages.Languages_LanguageSet languages_LanguageSet0 = Languages.Languages_LanguageSet.from(linkedHashSet0);
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty(languages_LanguageSet0);
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0, 2, 1);
      Rule.Rule_Phoneme rule_Phoneme0 = mock(Rule.Rule_Phoneme.class, new ViolatedAssumptionAnswer());
      Rule.Rule_Phoneme rule_Phoneme1 = new Rule.Rule_Phoneme(2, charBuffer0, languages_LanguageSet0, rule_Phoneme0);
      phoneticEngine_PhonemeBuilder0.apply(rule_Phoneme1, 0);
      assertFalse(rule_Phoneme1.equals((Object)rule_Phoneme0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("");
      Languages.Languages_LanguageSet languages_LanguageSet0 = Languages.Languages_LanguageSet.from(linkedHashSet0);
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty(languages_LanguageSet0);
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0, 2, 1);
      Rule.Rule_Phoneme rule_Phoneme0 = mock(Rule.Rule_Phoneme.class, new ViolatedAssumptionAnswer());
      Rule.Rule_Phoneme rule_Phoneme1 = new Rule.Rule_Phoneme(2, charBuffer0, languages_LanguageSet0, rule_Phoneme0);
      phoneticEngine_PhonemeBuilder0.apply(rule_Phoneme1, 1);
      assertFalse(rule_Phoneme1.equals((Object)rule_Phoneme0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Languages.Languages_LanguageSet languages_LanguageSet0 = Languages.Languages_LanguageSet.from(linkedHashSet0);
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty(languages_LanguageSet0);
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0, 2, 1);
      Rule.Rule_Phoneme rule_Phoneme0 = mock(Rule.Rule_Phoneme.class, new ViolatedAssumptionAnswer());
      Rule.Rule_Phoneme rule_Phoneme1 = new Rule.Rule_Phoneme(2, charBuffer0, languages_LanguageSet0, rule_Phoneme0);
      phoneticEngine_PhonemeBuilder0.apply(rule_Phoneme1, 279);
      assertFalse(rule_Phoneme1.equals((Object)rule_Phoneme0));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty((Languages.Languages_LanguageSet) null);
      phoneticEngine_PhonemeBuilder0.append("");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Languages.Languages_AnyLanguage languages_AnyLanguage0 = new Languages.Languages_AnyLanguage();
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder0 = PhoneticEngine.PhoneticEngine_PhonemeBuilder.empty(languages_AnyLanguage0);
      Set<Rule.Rule_Phoneme> set0 = phoneticEngine_PhonemeBuilder0.getPhonemes();
      PhoneticEngine.PhoneticEngine_PhonemeBuilder phoneticEngine_PhonemeBuilder1 = new PhoneticEngine.PhoneticEngine_PhonemeBuilder(0, set0, (Rule.Rule_Phoneme) null);
      assertFalse(phoneticEngine_PhonemeBuilder1.equals((Object)phoneticEngine_PhonemeBuilder0));
  }
}
