// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

open class B64 {
    // Fields Begin
    static let B64T_STRING: String = throw Exception('TODO')
    static let B64T_ARRAY: Array<Rune> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    static func b64from24bit(b2: Int8, b1: Int8, b0: Int8, outLen: Int64, buffer: Any): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

