// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

@Test
open class Blake3Test {
    // Fields Begin
    // Fields End

    // Methods Begin
    public func shouldThrowIllegalArgumentExceptionWhenIncorrectKeySize(): Unit {
        throw Exception('TODO')
    }

    private static func assertThrowsProperExceptionWithKeySize(keySize: Int64): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

