// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

open class DigestUtilsTest {
    // Fields Begin
    static let EMPTY_STRING: String = throw Exception('TODO')
    let testData: Array<Int8> = throw Exception('TODO')
    var testFile: Any = throw Exception('TODO')
    var testRandomAccessFile: Any = throw Exception('TODO')
    var testRandomAccessFileWrapper: Any = throw Exception('TODO')
    // Fields End

    // Methods Begin
    func getTestData(): Array<Int8> {
        throw Exception('TODO')
    }

    func getTestFile(): Any {
        throw Exception('TODO')
    }

    func getTestPath(): Any {
        throw Exception('TODO')
    }

    func getTestRandomAccessFile(): Any {
        throw Exception('TODO')
    }

    public func setUp(): Unit {
        throw Exception('TODO')
    }

    public func tearDown(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

