// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

open class Md5Crypt {
    // Fields Begin
    static let APR1_PREFIX: String = throw Exception('TODO')
    static let BLOCKSIZE: Int64 = throw Exception('TODO')
    static let MD5_PREFIX: String = throw Exception('TODO')
    static let ROUNDS: Int64 = throw Exception('TODO')
    // Fields End

    // Methods Begin
    // Methods End
}

