// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

@Test
open class MurmurHash2Test {
    // Fields Begin
    static let input: Array<Array<Int8>> = throw Exception('TODO')
    static let results32_standard: Array<Int64> = throw Exception('TODO')
    static let results32_seed: Array<Int64> = throw Exception('TODO')
    static let results64_standard: Array<Int64> = throw Exception('TODO')
    static let results64_seed: Array<Int64> = throw Exception('TODO')
    static let text: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testHash32ByteArrayIntInt(): Unit {
        throw Exception('TODO')
    }

    public func testHash32ByteArrayInt(): Unit {
        throw Exception('TODO')
    }

    public func testHash32String(): Unit {
        throw Exception('TODO')
    }

    public func testHash32StringIntInt(): Unit {
        throw Exception('TODO')
    }

    public func testHash64ByteArrayIntInt(): Unit {
        throw Exception('TODO')
    }

    public func testHash64ByteArrayInt(): Unit {
        throw Exception('TODO')
    }

    public func testHash64String(): Unit {
        throw Exception('TODO')
    }

    public func testHash64StringIntInt(): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

