// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

@Test
open class PureJavaCrc32CTest {
    // Fields Begin
    let crc: Any = throw Exception('TODO')
    let data: Array<Int8> = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public func testZeros(): Unit {
        throw Exception('TODO')
    }

    public func testOnes(): Unit {
        throw Exception('TODO')
    }

    public func testIncreasing(): Unit {
        throw Exception('TODO')
    }

    public func testDecreasing(): Unit {
        throw Exception('TODO')
    }

    private func check(expected: Int64): Unit {
        throw Exception('TODO')
    }

    // Methods End
}

