// Package: commons_codec.digest
package commons_codec.digest

// Imports Begin
// Imports End

@Test
open class XXHash32Test {
    // Fields Begin
    let file: Any = throw Exception('TODO')
    let expectedChecksum: String = throw Exception('TODO')
    // Fields End

    // Methods Begin
    public init(path: String, c: String) {
        throw Exception('TODO')
    }

    public static func factory(): Collection<Array<Any>> {
        throw Exception('TODO')
    }

    public func verifyChecksum(): Unit {
        throw Exception('TODO')
    }

    public func verifyIncrementalChecksum(): Unit {
        throw Exception('TODO')
    }

    private static func toByteArray(input: InputStream): Array<Int8> {
        throw Exception('TODO')
    }

    private static func copy(input: InputStream, output: OutputStream, buffersize: Int64): Int64 {
        throw Exception('TODO')
    }

    // Methods End
}

